name:                custom-monads
version:             0.1.0.0
github:              "githubuser/custom-monads"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/custom-monads#readme>

default-extensions:
  - BlockArguments
  - LambdaCase
  - ScopedTypeVariables
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - DeriveFunctor
  - RankNTypes

dependencies:
- base >= 4.7 && < 5
- transformers

library:
  source-dirs: src
  dependencies:
    - containers
    - text

executables:
  custom-monads-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - custom-monads

tests:
  custom-monads-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - custom-monads
